// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8VJPfCxLWmDV-AJpskpek2mFDjqlYZw4',
    appId: '1:451430336342:web:97dd3bbabbda8ab263f8f7',
    messagingSenderId: '451430336342',
    projectId: 'gangnam-laundry',
    authDomain: 'gangnam-laundry.firebaseapp.com',
    storageBucket: 'gangnam-laundry.firebasestorage.app',
    measurementId: 'G-33JLB6PS3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo0xoTKayXBAR46Uh-vDgQ99ht7uw_he4',
    appId: '1:451430336342:android:240c02c48400064a63f8f7',
    messagingSenderId: '451430336342',
    projectId: 'gangnam-laundry',
    storageBucket: 'gangnam-laundry.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2-AP-XmHD9rp-daJMvQCD7ETjeB5RMLY',
    appId: '1:451430336342:ios:51350275ad33dd6463f8f7',
    messagingSenderId: '451430336342',
    projectId: 'gangnam-laundry',
    storageBucket: 'gangnam-laundry.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2-AP-XmHD9rp-daJMvQCD7ETjeB5RMLY',
    appId: '1:451430336342:ios:51350275ad33dd6463f8f7',
    messagingSenderId: '451430336342',
    projectId: 'gangnam-laundry',
    storageBucket: 'gangnam-laundry.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8VJPfCxLWmDV-AJpskpek2mFDjqlYZw4',
    appId: '1:451430336342:web:141a27d3986ad09963f8f7',
    messagingSenderId: '451430336342',
    projectId: 'gangnam-laundry',
    authDomain: 'gangnam-laundry.firebaseapp.com',
    storageBucket: 'gangnam-laundry.firebasestorage.app',
    measurementId: 'G-S3FWZ6N879',
  );

}