// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6Mnfc26V2kiAzrcXWaDIgBRDLuM0VlN8',
    appId: '1:491138210534:web:21a2b7a249f26aa6caf927',
    messagingSenderId: '491138210534',
    projectId: 'modul6-fcm',
    authDomain: 'modul6-fcm.firebaseapp.com',
    storageBucket: 'modul6-fcm.firebasestorage.app',
    measurementId: 'G-HC4XYMZ24N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ07n1dpV1pdTP4-6gzXU387yXk3THGYE',
    appId: '1:491138210534:android:a80bb6ffa9d3264ecaf927',
    messagingSenderId: '491138210534',
    projectId: 'modul6-fcm',
    storageBucket: 'modul6-fcm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgOLxI8uJY4mX_M0QR2rTYTdkJnG5kH7Y',
    appId: '1:491138210534:ios:abf7ee312f5e86becaf927',
    messagingSenderId: '491138210534',
    projectId: 'modul6-fcm',
    storageBucket: 'modul6-fcm.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgOLxI8uJY4mX_M0QR2rTYTdkJnG5kH7Y',
    appId: '1:491138210534:ios:abf7ee312f5e86becaf927',
    messagingSenderId: '491138210534',
    projectId: 'modul6-fcm',
    storageBucket: 'modul6-fcm.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6Mnfc26V2kiAzrcXWaDIgBRDLuM0VlN8',
    appId: '1:491138210534:web:5cba4de17d9d6858caf927',
    messagingSenderId: '491138210534',
    projectId: 'modul6-fcm',
    authDomain: 'modul6-fcm.firebaseapp.com',
    storageBucket: 'modul6-fcm.firebasestorage.app',
    measurementId: 'G-KGWJLDKBD9',
  );

}